[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@chainlink/contracts=lib/chainlink/contracts",
]

# Etherscan settings 
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }

# RPC endpoints 
[rpc_endpoints]
mainnet = "${ETHEREUM_MAINNET_RPC_URL}"
sepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"
optimism = "${OP_SEPOLIA_RPC_URL}"


#match-path = "test/YoyoNft.t.sol"
#match-path = "test/YoyoAuction.t.sol"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
